version: '3'
services:
# Database - To run the DHIS2 postgres database
  db:
    image: ghcr.io/baosystems/postgis:13
    platform: linux/arm64
    command: postgres -c max_locks_per_transaction=100
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis2v41
      POSTGRES_PASSWORD: dhis
    volumes:
     - ./db/sierraleone/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
    - "5431:5432"

# DHIS2 - To run the DHIS2 core web services
  web:
    image: dhis2/core:2.41.0.0-rc
    volumes:
    - ./dhis.conf:/opt/dhis2/dhis.conf
    environment:
    - WAIT_FOR_DB_CONTAINER=db:5432 -t 0
    ports:
    - "8082:8080"
    depends_on:
    - db

# PGAdmin - To inspect and manage the database
#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@test.no
#      - PGADMIN_DEFAULT_PASSWORD=district
#    ports:
#      - "5050:80"
#    depends_on:
#        - db